name: gencosts
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=3.0.2
  - geopandas=0.6.2
  - numpy=1.17.3
  - osmnx=0.12.1
  - pandas=0.25.3
  - pip=19.3.1
  - rasterio=1.1.1
  - scipy=1.4.1
  - tqdm=4.41.1
  - pip:
    - census==0.8.13
    - jupyterlab==1.2.3
    - jupyterlab-server==1.0.6
